permalink: /:year/:month/:day/:title

highlighter: pygments
markdown: kramdown

title : Orbitist Portfolio
tagline: Latest Work from Orbitist
author : 
  name : Orbitist Support
  email : support@orbitist.com
  github : Orbitist
  twitter : TheOrbitist
  web : http://www.orbitist.com

production_url : orbitist.com/portfolio

baseurl : http://orbitist.com/portfolio
  
timezone : America/New_York